apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
  namespace: flask
  labels:
    app: flask-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      containers:
        - name: flask-hello
          image: 766796015930.dkr.ecr.ap-southeast-1.amazonaws.com/flask-hello:66231210b235dd39272fd68adf00093f9b19c706
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15