apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
  namespace: flask
  labels:
    app: flask-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      imagePullSecrets:
      - name: harbor-cred
      containers:
        - name: flask-hello
          image: 10.10.1.163/flask-hello/flask-hello:8d4a8d7
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15